services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: devrolebot
      POSTGRES_PASSWORD: devrolebot
      POSTGRES_DB: devrolebot
    volumes:
      - "postgresdata:/var/lib/postgresql/data/"
    command: ["postgres", "-c", "log_statement=all"]
    env_file: ./.env
  bot:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - "./:/opt/role-bot/"
    restart: always
volumes:
  postgresdata:
    driver: local
