services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: devrolebot
      POSTGRES_PASSWORD: devrolebot
      POSTGRES_DB: devrolebot
    volumes:
      - "postgresdata:/var/lib/postgresql/data/"
  bot:
    image: node:16.6.2
    volumes:
      - "./:/opt/role-bot/"
    working_dir: /opt/role-bot/
    command: ./scripts/entrypoint-dev.sh
    restart: always
    env_file: ./.env
volumes:
  postgresdata:
    driver: local
