[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "role-bot"
dynamic = ["version"]
description = ''
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
keywords = []
authors = [
  { name = "Noah Huppert", email = "3323504+Noah-Huppert@users.noreply.github.com" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = []

[project.urls]
Documentation = "https://github.com/Noah Huppert/role-bot#readme"
Issues = "https://github.com/Noah Huppert/role-bot/issues"
Source = "https://github.com/Noah Huppert/role-bot"

[tool.hatch.version]
path = "src/role_bot/__about__.py"

[tool.hatch.envs.types]
extra-dependencies = [
  "mypy>=1.0.0",
]
[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/role_bot tests}"

[tool.coverage.run]
source_pkgs = ["role_bot", "tests"]
branch = true
parallel = true
omit = [
  "src/role_bot/__about__.py",
]

[tool.coverage.paths]
role_bot = ["src/role_bot", "*/role-bot/src/role_bot"]
tests = ["tests", "*/role-bot/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]
